In [1]:
from numpy import *
import scipy.linalg

a = array([[1,2,3], [4,5,6]])

In [2]:
a.ndim

2

In [3]:
a.size

6

In [4]:
a.shape

(2, 3)

In [5]:
a.shape[2 - 1]

3

In [6]:
array([[1.,2.,3.], [4.,5.,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
a = array([[1,2,3], [4,5,6]])
b = array([[7,8], [9,10]])
c = array([11,12,13])
d = array([14,15])
block([[a,b], [c,d]])

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
a = array([1,2,3])
a[-1]

3

In [9]:
a = array([[1.,2.,3.,4.,5.], [4.,5.,6.,7.,8.]])
a[1,4]

8.0

In [10]:
a[1]

array([4., 5., 6., 7., 8.])

In [11]:
a = random.rand(10,10)
a[0:5]

array([[0.11091346, 0.18813278, 0.38886451, 0.01564434, 0.65630107,
        0.89487869, 0.39196738, 0.65118397, 0.38013103, 0.38642712],
       [0.0615329 , 0.05491462, 0.6786101 , 0.34833783, 0.86622937,
        0.65896189, 0.21668015, 0.84099304, 0.77314152, 0.78416086],
       [0.47623283, 0.45202318, 0.50298568, 0.77562004, 0.86088117,
        0.02823798, 0.58613231, 0.24811471, 0.41465849, 0.86202428],
       [0.63603256, 0.22084435, 0.29374814, 0.73921845, 0.0314483 ,
        0.8692037 , 0.56419239, 0.22057753, 0.90365472, 0.47762319],
       [0.55111013, 0.58163412, 0.30764424, 0.41473802, 0.44558266,
        0.42453037, 0.20664003, 0.24016248, 0.20636133, 0.22098645]])

In [12]:
a = random.rand(10,10)
a[-5:]

array([[0.39505558, 0.29493683, 0.124675  , 0.22400932, 0.67976444,
        0.99289604, 0.68005499, 0.97099117, 0.6125787 , 0.22213548],
       [0.76810448, 0.9693669 , 0.02677607, 0.59034354, 0.75207725,
        0.00545877, 0.45787451, 0.19228036, 0.89006725, 0.21702255],
       [0.40432123, 0.26661213, 0.85981907, 0.17463352, 0.12920083,
        0.46072097, 0.7191831 , 0.21069979, 0.1447597 , 0.10630844],
       [0.65668841, 0.45894297, 0.15306643, 0.31711827, 0.12957445,
        0.9381938 , 0.49013859, 0.71316851, 0.32307456, 0.4583544 ],
       [0.78164092, 0.54655258, 0.80033144, 0.53147133, 0.32622476,
        0.26039577, 0.31101405, 0.31345462, 0.96317355, 0.09404395]])

In [13]:
a[0:3][:,4:9]

array([[0.30940937, 0.21808411, 0.79814726, 0.35993621, 0.05813967],
       [0.93532383, 0.01972792, 0.66321781, 0.78896412, 0.3488759 ],
       [0.40320558, 0.43492525, 0.07858936, 0.80535221, 0.5886861 ]])

In [14]:
a[ix_([1,3,4],[0,2])]

array([[0.87517631, 0.22576506],
       [0.22277763, 0.24092253],
       [0.27943868, 0.31206781]])

In [15]:
a[0:5:2,:]

array([[0.3640264 , 0.06822797, 0.19762853, 0.38564732, 0.30940937,
        0.21808411, 0.79814726, 0.35993621, 0.05813967, 0.5303719 ],
       [0.41857048, 0.51787955, 0.98122613, 0.49356253, 0.40320558,
        0.43492525, 0.07858936, 0.80535221, 0.5886861 , 0.6635198 ],
       [0.27943868, 0.86686448, 0.31206781, 0.98441533, 0.67002055,
        0.274018  , 0.57017336, 0.57793346, 0.79752976, 0.37539037]])

In [16]:
a[ ::2,:]

array([[0.3640264 , 0.06822797, 0.19762853, 0.38564732, 0.30940937,
        0.21808411, 0.79814726, 0.35993621, 0.05813967, 0.5303719 ],
       [0.41857048, 0.51787955, 0.98122613, 0.49356253, 0.40320558,
        0.43492525, 0.07858936, 0.80535221, 0.5886861 , 0.6635198 ],
       [0.27943868, 0.86686448, 0.31206781, 0.98441533, 0.67002055,
        0.274018  , 0.57017336, 0.57793346, 0.79752976, 0.37539037],
       [0.76810448, 0.9693669 , 0.02677607, 0.59034354, 0.75207725,
        0.00545877, 0.45787451, 0.19228036, 0.89006725, 0.21702255],
       [0.65668841, 0.45894297, 0.15306643, 0.31711827, 0.12957445,
        0.9381938 , 0.49013859, 0.71316851, 0.32307456, 0.4583544 ]])

In [17]:
a[ ::-1,:]

array([[0.78164092, 0.54655258, 0.80033144, 0.53147133, 0.32622476,
        0.26039577, 0.31101405, 0.31345462, 0.96317355, 0.09404395],
       [0.65668841, 0.45894297, 0.15306643, 0.31711827, 0.12957445,
        0.9381938 , 0.49013859, 0.71316851, 0.32307456, 0.4583544 ],
       [0.40432123, 0.26661213, 0.85981907, 0.17463352, 0.12920083,
        0.46072097, 0.7191831 , 0.21069979, 0.1447597 , 0.10630844],
       [0.76810448, 0.9693669 , 0.02677607, 0.59034354, 0.75207725,
        0.00545877, 0.45787451, 0.19228036, 0.89006725, 0.21702255],
       [0.39505558, 0.29493683, 0.124675  , 0.22400932, 0.67976444,
        0.99289604, 0.68005499, 0.97099117, 0.6125787 , 0.22213548],
       [0.27943868, 0.86686448, 0.31206781, 0.98441533, 0.67002055,
        0.274018  , 0.57017336, 0.57793346, 0.79752976, 0.37539037],
       [0.22277763, 0.16619594, 0.24092253, 0.53462511, 0.73634431,
        0.21913135, 0.38333461, 0.07744886, 0.25468506, 0.92797269],
       [0.41857048, 0.51787955, 0.9812261

In [18]:
a[r_[:len(a),0]]

array([[0.3640264 , 0.06822797, 0.19762853, 0.38564732, 0.30940937,
        0.21808411, 0.79814726, 0.35993621, 0.05813967, 0.5303719 ],
       [0.87517631, 0.71187758, 0.22576506, 0.33905685, 0.93532383,
        0.01972792, 0.66321781, 0.78896412, 0.3488759 , 0.37721113],
       [0.41857048, 0.51787955, 0.98122613, 0.49356253, 0.40320558,
        0.43492525, 0.07858936, 0.80535221, 0.5886861 , 0.6635198 ],
       [0.22277763, 0.16619594, 0.24092253, 0.53462511, 0.73634431,
        0.21913135, 0.38333461, 0.07744886, 0.25468506, 0.92797269],
       [0.27943868, 0.86686448, 0.31206781, 0.98441533, 0.67002055,
        0.274018  , 0.57017336, 0.57793346, 0.79752976, 0.37539037],
       [0.39505558, 0.29493683, 0.124675  , 0.22400932, 0.67976444,
        0.99289604, 0.68005499, 0.97099117, 0.6125787 , 0.22213548],
       [0.76810448, 0.9693669 , 0.02677607, 0.59034354, 0.75207725,
        0.00545877, 0.45787451, 0.19228036, 0.89006725, 0.21702255],
       [0.40432123, 0.26661213, 0.8598190

In [19]:
a.T

array([[0.3640264 , 0.87517631, 0.41857048, 0.22277763, 0.27943868,
        0.39505558, 0.76810448, 0.40432123, 0.65668841, 0.78164092],
       [0.06822797, 0.71187758, 0.51787955, 0.16619594, 0.86686448,
        0.29493683, 0.9693669 , 0.26661213, 0.45894297, 0.54655258],
       [0.19762853, 0.22576506, 0.98122613, 0.24092253, 0.31206781,
        0.124675  , 0.02677607, 0.85981907, 0.15306643, 0.80033144],
       [0.38564732, 0.33905685, 0.49356253, 0.53462511, 0.98441533,
        0.22400932, 0.59034354, 0.17463352, 0.31711827, 0.53147133],
       [0.30940937, 0.93532383, 0.40320558, 0.73634431, 0.67002055,
        0.67976444, 0.75207725, 0.12920083, 0.12957445, 0.32622476],
       [0.21808411, 0.01972792, 0.43492525, 0.21913135, 0.274018  ,
        0.99289604, 0.00545877, 0.46072097, 0.9381938 , 0.26039577],
       [0.79814726, 0.66321781, 0.07858936, 0.38333461, 0.57017336,
        0.68005499, 0.45787451, 0.7191831 , 0.49013859, 0.31101405],
       [0.35993621, 0.78896412, 0.8053522

In [20]:
a.conj().T

array([[0.3640264 , 0.87517631, 0.41857048, 0.22277763, 0.27943868,
        0.39505558, 0.76810448, 0.40432123, 0.65668841, 0.78164092],
       [0.06822797, 0.71187758, 0.51787955, 0.16619594, 0.86686448,
        0.29493683, 0.9693669 , 0.26661213, 0.45894297, 0.54655258],
       [0.19762853, 0.22576506, 0.98122613, 0.24092253, 0.31206781,
        0.124675  , 0.02677607, 0.85981907, 0.15306643, 0.80033144],
       [0.38564732, 0.33905685, 0.49356253, 0.53462511, 0.98441533,
        0.22400932, 0.59034354, 0.17463352, 0.31711827, 0.53147133],
       [0.30940937, 0.93532383, 0.40320558, 0.73634431, 0.67002055,
        0.67976444, 0.75207725, 0.12920083, 0.12957445, 0.32622476],
       [0.21808411, 0.01972792, 0.43492525, 0.21913135, 0.274018  ,
        0.99289604, 0.00545877, 0.46072097, 0.9381938 , 0.26039577],
       [0.79814726, 0.66321781, 0.07858936, 0.38333461, 0.57017336,
        0.68005499, 0.45787451, 0.7191831 , 0.49013859, 0.31101405],
       [0.35993621, 0.78896412, 0.8053522

In [21]:
a = array([[1,2],[3,4]])
b = array([[5,6],[7,8]])
a @ b

array([[19, 22],
       [43, 50]])

In [22]:
a * b

array([[ 5, 12],
       [21, 32]])

In [23]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [24]:
a ** 3

array([[ 1,  8],
       [27, 64]])

In [25]:
(a > 1)

array([[False,  True],
       [ True,  True]])

In [26]:
nonzero(a > 1)

(array([0, 1, 1]), array([1, 0, 1]))

In [28]:
a[:,nonzero(a > 1)[0]]

array([[1, 2, 2],
       [3, 4, 4]])

In [33]:
a[:,(a.T > 1)[0]]

array([[2],
       [4]])

In [34]:
a[a < 1] = 0

In [35]:
a * (a>0.5)

array([[1, 2],
       [3, 4]])

In [36]:
a[:] = 3
a

array([[3, 3],
       [3, 3]])

In [37]:
y = a.copy()
y

array([[3, 3],
       [3, 3]])

In [39]:
y = a[1,:].copy()
y

array([3, 3])

In [40]:
y = a.flatten()
y

array([3, 3, 3, 3])

In [41]:
arange(1.,11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
arange(1.,11.)[:, newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [44]:
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [46]:
ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
diag(a)

array([3, 3])

In [49]:
diag(a,0)

array([3, 3])

In [50]:
random.rand(3,4)

array([[0.47145052, 0.34461856, 0.28743758, 0.89729863],
       [0.6419616 , 0.81955975, 0.03043099, 0.74595539],
       [0.36148784, 0.2204665 , 0.53011759, 0.10057815]])

In [51]:
linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [52]:
mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [53]:
ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [54]:
meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [55]:
ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [57]:
tile(a, (1, 2))

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [58]:
concatenate((a,b),1) 

array([[3, 3, 5, 6],
       [3, 3, 7, 8]])

In [59]:
concatenate((a,b)) 

array([[3, 3],
       [3, 3],
       [5, 6],
       [7, 8]])

In [60]:
a.max()

3

In [61]:
a.max(0)

array([3, 3])

In [62]:
a.max(1)

array([3, 3])

In [63]:
maximum(a, b)

array([[5, 6],
       [7, 8]])

In [64]:
sqrt(a @ a)

array([[4.24264069, 4.24264069],
       [4.24264069, 4.24264069]])

In [65]:
logical_and(a,b)

array([[ True,  True],
       [ True,  True]])

In [66]:
logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [67]:
a & b

array([[1, 2],
       [3, 0]])

In [68]:
a | b

array([[ 7,  7],
       [ 7, 11]])

In [70]:
a = array([[1,2],[3,4]])
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [71]:
linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [72]:
linalg.matrix_rank(a)

2

In [73]:
linalg.solve(a,b)

array([[-3., -4.],
       [ 4.,  5.]])

In [103]:
U, S, Vh = linalg.svd(a)
V = Vh.T
U
S
Vh
V
print(V)
print(U)
print(S)
print(Vh)

[[-0.71339738  0.70075972]
 [-0.70075972 -0.71339738]]
[[-0.92806508 -0.37241806]
 [-0.37241806  0.92806508]]
[1.09531835 0.10653957]
[[-0.71339738 -0.70075972]
 [ 0.70075972 -0.71339738]]


In [79]:
a = random.rand(2,2)
linalg.cholesky(a).T

array([[0.83509476, 0.43144147],
       [0.        , 0.17079799]])

In [83]:
D,V = linalg.eig(a)
print(D)
print(V)

[ 1.02639118 -0.11369422]
[[ 0.91388863 -0.67431783]
 [ 0.40596499  0.73844124]]


In [82]:
D,V = scipy.linalg.eig(a,b)
print(D)
print(V)

[0.17266471+0.1689209j 0.17266471-0.1689209j]
[[ 0.77450301-0.02859999j  0.77450301+0.02859999j]
 [-0.63104809-0.03324815j -0.63104809+0.03324815j]]


In [84]:
Q,R = scipy.linalg.qr(a)
print(Q)
print(R)

[[-0.88843639 -0.45899977]
 [-0.45899977  0.88843639]]
[[-0.78495577 -0.75684635]
 [ 0.         -0.1486641 ]]


In [86]:
LU,P=scipy.linalg.lu_factor(a)
print(LU)
print(P)

[[ 0.69738326  0.74064662]
 [ 0.51663774 -0.1673323 ]]
[0 1]


In [92]:
from scipy import *
scipy.fft.fft(a)

array([[ 1.43802988-0.j, -0.04326336-0.j],
       [ 0.57560822-0.j,  0.14498082-0.j]])

In [93]:
scipy.fft.ifft(a)

array([[ 0.71901494-0.j, -0.02163168-0.j],
       [ 0.28780411-0.j,  0.07249041-0.j]])

In [102]:
import numpy as np
np.sort(a)

array([[0.69738326, 0.74064662],
       [0.2153137 , 0.36029452]])

In [101]:
import numpy as np
I = np.argsort(a[:,1])
b=a[I,:]
print(I)
print(b)

[1 0]
[[0.36029452 0.2153137 ]
 [0.69738326 0.74064662]]


In [110]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
print(m)
print(c)

0.9999999999999999
-0.9499999999999997


In [114]:
from scipy import signal
signal.resample(a, len(a))

array([1., 2.])

In [116]:
import numpy as np
np.unique(a)

array([1, 2])

In [117]:
a.squeeze()

array([1, 2])